Pandas- Data Frame and Series


pandas is a powerful data manipulation library in python, widely used for data analysis and data cleaning. it provided two primary data structures. series and dataframe.
A series is a one dimentional array like object 
while a data frame is a two dimentional ,size mutable and potentionally heterogeneous tabular data structure with labled axes (rows and columns)

In [1]:
import pandas as pd

In [2]:
## Series
## Series is one-dimantional array like object that can hold any data type. It is similar to a column in table.



data=[1,2,3,4,5]

series=pd.Series(data)


print("Series: \n",series)

Series:
 0    1
1    2
2    3
3    4
4    5
dtype: int64

In [4]:
## Create a series from a dictionary elements

data={"a":1,"b":2,"c":3}

print(pd.Series(data))

a    1
b    2
c    3
dtype: int64

In [7]:
data=[10,20,30]
index=['a','b','c']

pd.Series(data,index)

a    10
b    20
c    30
dtype: int64

In [ ]:
## Data Frame

## Create a dataframe from dictionary of list


data={
    "Name":['Kajal','Jon',"jack"],
    "Age":[25,30,45],
    "City":['Pune','Mumbai','Nashik']
}

df=pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age    City
0  Kajal   25    Pune
1    Jon   30  Mumbai
2   jack   45  Nashik
<class 'pandas.DataFrame'>

In [13]:
## Create a data frame from list of dictionaries

data=[
    {"Name":'Kajal',"Age":25,"City":'Pune'},
    {"Name":'Jon',"Age":25,"City":'Mumbai'},
    {"Name":'JAck',"Age":25,"City":'Nashik'},
    {"Name":'Mac',"Age":25,"City":'Pune'},
    {"Name":'PQR',"Age":25,"City":'Pune'}
]

df=pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age    City
0  Kajal   25    Pune
1    Jon   25  Mumbai
2   JAck   25  Nashik
3    Mac   25    Pune
4    PQR   25    Pune
<class 'pandas.DataFrame'>

In [ ]:
## create dataframe from csv

df=pd.read_csv('customers.csv')
df.head(5)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,2022-01-30,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,+1-846-706-2218,605.413.3198,vkemp@ferrell.com,2021-07-10,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,2021-09-18,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,2021-08-11,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/

In [16]:
df.tail(5)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,2022-01-30,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,+1-846-706-2218,605.413.3198,vkemp@ferrell.com,2021-07-10,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,2021-09-18,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,2021-08-11,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/

In [79]:
## Accessing Data from dataframe
data={
    "Name":['Kajal','Jon',"jack"],
    "Age":[25,30,45],
    "City":['Pune','Mumbai','Nashik']
}

df=pd.DataFrame(data)
print(df)

    Name  Age    City
0  Kajal   25    Pune
1    Jon   30  Mumbai
2   jack   45  Nashik

In [43]:
df['Name']

0    Kajal
1      Jon
2     jack
Name: Name, dtype: str

In [ ]:
type(df['City'])  # It is becoming the series

pandas.Series

In [34]:
df.loc[0]

Name    Kajal
Age        25
City     Pune
Name: 0, dtype: object

In [54]:
df.iloc[0]

Name    Kajal
Age        25
City     Pune
Name: 0, dtype: object

In [45]:
### Accessing a specified element

df

    Name  Age    City
0  Kajal   25    Pune
1    Jon   30  Mumbai
2   jack   45  Nashik

In [51]:
df.at[1,'Age']

np.int64(30)

In [55]:
## Accesing a specified element using iat


df.iat[2,2]

'Nashik'

In [61]:
### Data Manupulation with DataFrame

# Adding a column

df['Salary']=[10000,130002,12193293]

df

    Name  Age    City    Salary
0  Kajal   25    Pune     10000
1    Jon   30  Mumbai    130002
2   jack   45  Nashik  12193293

In [66]:
## Remove a column
df.drop('Salary',axis=1,inplace=True)

# it is not permenant operation
#if we want to remove a column permenantly use inplace=true

In [78]:
## ADD age to the column

df['Age']=df['Age']+1
print(df)

   Name  Age    City
1   Jon   33  Mumbai
2  jack   48  Nashik

In [80]:
df

    Name  Age    City
0  Kajal   25    Pune
1    Jon   30  Mumbai
2   jack   45  Nashik

In [81]:
# Drop based on rows

df.drop(0,inplace=True)

In [82]:
df

   Name  Age    City
1   Jon   30  Mumbai
2  jack   45  Nashik

In [84]:
df=pd.read_csv('customers.csv')

print("Description: \n ",df.describe)

Description:
  <bound method NDFrame.describe of     Index      Customer Id First Name Last Name  \
0       1  DD37Cf93aecA6Dc     Sheryl    Baxter
1       2  1Ef7b82A4CAAD10    Preston    Lozano
2       3  6F94879bDAfE5a6        Roy     Berry
3       4  5Cef8BFA16c5e3c      Linda     Olsen
4       5  053d585Ab6b3159     Joanna    Bender
..    ...              ...        ...       ...
95     96  cb8E23e48d22Eae       Karl     Greer
96     97  CeD220bdAaCfaDf       Lynn  Atkinson
97     98  28CDbC0dFe4b1Db       Fred    Guerra
98     99  c23d1D9EE8DEB0A     Yvonne    Farmer
99    100  2354a0E336A91A1   Clarence    Haynes

                            Company               City  \
0                   Rasmussen Group       East Leonard
1                       Vega-Gentry  East Jimmychester
2                     Murillo-Perry      Isabelborough
3   Dominguez, Mcmillan and Donovan         Bensonview
4          Martin, Lang and Andrade     West Priscilla
..                              ...                ...
95                        Carey LLC       East Richard
96            Ware, Burns and Oneal       New Bradview
97                    Schmitt-Jones         Ortegaland
98               Fitzgerald-Harrell    Lake Elijahview
99               Le, Nash and Cross          Judymouth

                       Country                 Phone 1  \
0                        Chile            229.077.5154
1                     Djibouti              5153435776
2          Antigua and Barbuda         +1-539-402-0259
3           Dominican Republic  001-808-617-6467x12895
4   Slovakia (Slovak Republic)  001-234-203-0635x76146
..                         ...                     ...
95                      Guyana     (188)169-1674x58692
96                   Sri Lanka         +1-846-706-2218
97             Solomon Islands    +1-753-067-8419x7170
98                       Aruba           (530)311-9786
99                    Honduras           (753)813-6941

                   Phone 2                           Email Subscription Date  \
0         397.884.0519x718        zunigavanessa@smith.info        2020-08-24
1         686-620-1820x944                 vmata@colon.com        2021-04-23
2      (496)978-3969x58947             beckycarr@hogan.com        2020-03-25
3          +1-813-324-8756     stanleyblackwell@benson.org        2020-06-02
4    001-199-446-3860x3486         colinalvarado@miles.net        2021-04-17
..                     ...                             ...               ...
95    001-841-293-3519x614                hhart@jensen.com        2022-01-30
96            605.413.3198               vkemp@ferrell.com        2021-07-10
97   +1-632-666-7507x92121                swagner@kane.org        2021-09-18
98  001-869-452-0943x12424  mccarthystephen@horn-green.biz        2021-08-11
99            783.639.1472          colleen91@faulkner.biz        2020-03-11

                              Website
0          http://www.stephenson.com/
1               http://www.hobbs.com/
2            http://www.lawrence.com/
3          http://www.good-lyons.com/
4         https://goodwin-ingram.com/
..                                ...
95            http://hayes-perez.com/
96         https://novak-allison.com/
97              https://www.ross.com/
98               http://watkins.info/
99  http://www.hatfield-saunders.net/

[100 rows x 12 columns]>