Data Manipulation and Analysis with pandas


Data manipulation and analysis are tasks in nay data science or data analysis project. Pandas provides a wide range of functions for data manipulation and analysus making it easier to clean transform and extract insights from data. In this lesson we will cover various data manipulation and analysis techniques usingg pandas.

In [2]:
import pandas as pd

In [5]:
df = pd.read_csv('customers.csv')

df.tail(5) # last 5 rows

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,2022-01-30,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,+1-846-706-2218,605.413.3198,vkemp@ferrell.com,2021-07-10,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,2021-09-18,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,2021-08-11,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/

In [4]:
df.head(5) # FIrst 5 rows

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/

In [6]:
df.describe

<bound method NDFrame.describe of     Index      Customer Id First Name Last Name  \
0       1  DD37Cf93aecA6Dc     Sheryl    Baxter
1       2  1Ef7b82A4CAAD10    Preston    Lozano
2       3  6F94879bDAfE5a6        Roy     Berry
3       4  5Cef8BFA16c5e3c      Linda     Olsen
4       5  053d585Ab6b3159     Joanna    Bender
..    ...              ...        ...       ...
95     96  cb8E23e48d22Eae       Karl     Greer
96     97  CeD220bdAaCfaDf       Lynn  Atkinson
97     98  28CDbC0dFe4b1Db       Fred    Guerra
98     99  c23d1D9EE8DEB0A     Yvonne    Farmer
99    100  2354a0E336A91A1   Clarence    Haynes

                            Company               City  \
0                   Rasmussen Group       East Leonard
1                       Vega-Gentry  East Jimmychester
2                     Murillo-Perry      Isabelborough
3   Dominguez, Mcmillan and Donovan         Bensonview
4          Martin, Lang and Andrade     West Priscilla
..                              ...                ...
95                        Carey LLC       East Richard
96            Ware, Burns and Oneal       New Bradview
97                    Schmitt-Jones         Ortegaland
98               Fitzgerald-Harrell    Lake Elijahview
99               Le, Nash and Cross          Judymouth

                       Country                 Phone 1  \
0                        Chile            229.077.5154
1                     Djibouti              5153435776
2          Antigua and Barbuda         +1-539-402-0259
3           Dominican Republic  001-808-617-6467x12895
4   Slovakia (Slovak Republic)  001-234-203-0635x76146
..                         ...                     ...
95                      Guyana     (188)169-1674x58692
96                   Sri Lanka         +1-846-706-2218
97             Solomon Islands    +1-753-067-8419x7170
98                       Aruba           (530)311-9786
99                    Honduras           (753)813-6941

                   Phone 2                           Email Subscription Date  \
0         397.884.0519x718        zunigavanessa@smith.info        2020-08-24
1         686-620-1820x944                 vmata@colon.com        2021-04-23
2      (496)978-3969x58947             beckycarr@hogan.com        2020-03-25
3          +1-813-324-8756     stanleyblackwell@benson.org        2020-06-02
4    001-199-446-3860x3486         colinalvarado@miles.net        2021-04-17
..                     ...                             ...               ...
95    001-841-293-3519x614                hhart@jensen.com        2022-01-30
96            605.413.3198               vkemp@ferrell.com        2021-07-10
97   +1-632-666-7507x92121                swagner@kane.org        2021-09-18
98  001-869-452-0943x12424  mccarthystephen@horn-green.biz        2021-08-11
99            783.639.1472          colleen91@faulkner.biz        2020-03-11

                              Website
0          http://www.stephenson.com/
1               http://www.hobbs.com/
2            http://www.lawrence.com/
3          http://www.good-lyons.com/
4         https://goodwin-ingram.com/
..                                ...
95            http://hayes-perez.com/
96         https://novak-allison.com/
97              https://www.ross.com/
98               http://watkins.info/
99  http://www.hatfield-saunders.net/

[100 rows x 12 columns]>

In [7]:
df.dtypes

Index                int64
Customer Id            str
First Name             str
Last Name              str
Company                str
City                   str
Country                str
Phone 1                str
Phone 2                str
Email                  str
Subscription Date      str
Website                str
dtype: object

In [ ]:
### Handling Missing Values

df.isnull().any(axis=1)

Index                False
Customer Id          False
First Name           False
Last Name            False
Company              False
City                 False
Country              False
Phone 1              False
Phone 2              False
Email                False
Subscription Date    False
Website              False
dtype: bool

In [12]:
df.isnull().any()

Index                False
Customer Id          False
First Name           False
Last Name            False
Company              False
City                 False
Country              False
Phone 1              False
Phone 2              False
Email                False
Subscription Date    False
Website              False
dtype: bool

In [13]:
df.isnull().sum()

Index                0
Customer Id          0
First Name           0
Last Name            0
Company              0
City                 0
Country              0
Phone 1              0
Phone 2              0
Email                0
Subscription Date    0
Website              0
dtype: int64

In [ ]:
### fill the missing values by some values

df.fillna(0)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,2022-01-30,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,+1-846-706-2218,605.413.3198,vkemp@ferrell.com,2021-07-10,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,2021-09-18,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,2021-08-11,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/

In [16]:
### Filling the missing value by the mean of the column value


# df['Sales_fillNa']=df['Sales'] .fillna(df['Sales'].mean())

In [ ]:
### Renaming column  
# give a key value pair 

df=df.rename(columns={'Subscription Date':'Admitted Date'})
df.head(2)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Admitted Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/

In [26]:
## Change the data type
df['Value']=1000

In [27]:
df.head(5)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Admitted Date,Website,Value
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/,1000
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/,1000
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/,1000
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/,1000
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/,1000

In [28]:
df.dtypes

Index            int64
Customer Id        str
First Name         str
Last Name          str
Company            str
City               str
Country            str
Phone 1            str
Phone 2            str
Email              str
Admitted Date      str
Website            str
Value            int64
dtype: object

In [31]:
df['Value_New']=df['Value'].astype(float)

df.dtypes

Index              int64
Customer Id          str
First Name           str
Last Name            str
Company              str
City                 str
Country              str
Phone 1              str
Phone 2              str
Email                str
Admitted Date        str
Website              str
Value              int64
Value_New        float64
dtype: object

In [33]:
df['Value_New'] = df['Value'].apply(lambda x:x*2)
df.head(5)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Admitted Date,Website,Value,Value_New
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/,1000,2000
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/,1000,2000
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/,1000,2000
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/,1000,2000
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/,1000,2000

In [36]:
### Data Aggregating and Grouping

grouped_mean=df.groupby('Country')['Value'].mean()
print(grouped_mean)

Country
Albania                1000.0
Algeria                1000.0
Anguilla               1000.0
Antigua and Barbuda    1000.0
Aruba                  1000.0
                        ...
Uzbekistan             1000.0
Vietnam                1000.0
Western Sahara         1000.0
Yemen                  1000.0
Zimbabwe               1000.0
Name: Value, Length: 85, dtype: float64

In [38]:
grouped2=df.groupby(['Country','Admitted Date'])['Value'].sum()
print(grouped2)

Country              Admitted Date
Albania              2021-04-06       1000
Algeria              2021-03-27       1000
Anguilla             2021-06-29       1000
Antigua and Barbuda  2020-03-25       1000
Aruba                2021-08-11       1000
                                      ...
Vietnam              2020-11-29       1000
Western Sahara       2021-03-10       1000
Yemen                2021-04-15       1000
Zimbabwe             2020-08-22       1000
                     2021-09-15       1000
Name: Value, Length: 100, dtype: int64

In [ ]:
### Multiple Agregation operation Together

grouped_agg=df.groupby(['Country'])['Value'].agg(['mean','sum','count'])
print(grouped_agg)

                       mean   sum  count
Country
Albania              1000.0  1000      1
Algeria              1000.0  1000      1
Anguilla             1000.0  1000      1
Antigua and Barbuda  1000.0  1000      1
Aruba                1000.0  1000      1
...                     ...   ...    ...
Uzbekistan           1000.0  1000      1
Vietnam              1000.0  1000      1
Western Sahara       1000.0  1000      1
Yemen                1000.0  1000      1
Zimbabwe             1000.0  2000      2

[85 rows x 3 columns]

In [40]:
 ### Merging and Joining Dataframes

#create sample dataframes

df1=pd.DataFrame({'Keys':['A','B','C'],'Value1':[1,2,3]})
df2=pd.DataFrame({'Keys':['A','B','D'],'Value2':[4,5,6]})

df1

  Keys  Value1
0    A       1
1    B       2
2    C       3

In [41]:
df2

  Keys  Value2
0    A       4
1    B       5
2    D       6

In [43]:
## Merge DataFrame on the key Column

pd.merge(df1,df2,on='Keys',how='inner')

  Keys  Value1  Value2
0    A       1       4
1    B       2       5

In [44]:
pd.merge(df1,df2,on='Keys',how='outer')

  Keys  Value1  Value2
0    A     1.0     4.0
1    B     2.0     5.0
2    C     3.0     NaN
3    D     NaN     6.0

In [45]:
pd.merge(df1,df2,on='Keys',how='left')

  Keys  Value1  Value2
0    A       1     4.0
1    B       2     5.0
2    C       3     NaN

In [46]:
pd.merge(df1,df2,on='Keys',how='right')

  Keys  Value1  Value2
0    A     1.0       4
1    B     2.0       5
2    D     NaN       6